### PR TITLE
IE11 Support

### PR DESCRIPTION
**Pull request by dballance**
- [x] Update README with instructions
- [x] Make demo site working in IE11
- [x] Make plunker examples work in IE11
- [x] Make tests pass in IE11 (Locally/Saucelabs)

Tests pass locally and in CI, but will need to be tested on Saucelabs. I do not have credentials.

This also changes polyfills used by the test app and by the demo site. IE11 just crumbles when `es6-shim` is utilized - as was mentioned in the #150 `README.md`. Using `core-js`, it runs and tests much faster.

### CODE REVIEW

**Comment by bekos** [comment]
@dballance Awesome!
@sadesyllas Can u review and confirm that this is working locally for IE11?

**Comment by bekos** [comment]
Saucelabs is green! 🎉
https://travis-ci.org/ng-lightning/ng-lightning/builds/147451794

**Comment by sadesyllas** [comment]
@bekos, it's working fine in IE11 apart from a minor nuisance with the spinners. The spinners seem to become active after hovering over them but it must not be relevant to this pr.
@dballance, great work! Thanks!

**Comment by bekos** [comment]
@dballance Your PR landed in master. Thx!

**Comment by dballance** [comment]
@sadesyllas I remember that issue now that you mention it! Should have added it to the notes on the PR.

@bekos :+1:

**Pull request closed without merging**
