### PR TITLE
Angular 11 upgrade

### PR DESCRIPTION
**Pull request by niralpokal**
Update the package to Angular 11

### CODE REVIEW

**Comment by niralpokal** [comment]
@bekos I took a look at the build error and it looks like ngcc is complaining about `type: 'alert' | 'toast'` in this line
`  constructor(private element: ElementRef, private renderer: Renderer2, private cd: ChangeDetectorRef, type: 'alert' | 'toast') {
` in `notify.ts `.

 If I change the type to string it works fine. I tried making `alert' | 'toast'` into a type and it still failed. Do you have any thoughts on how I should fix this?

**Comment by aelders-ncino** [comment]
Any updates on this? We finally have the opportunity to upgrade out projects to Angular 11, but ng-lightning might be holding us back. I'd prefer to upgrade when ng-lightning officially supports ng 11.

**Comment by elvisbegovic** [comment]
cc @bekos

**Comment by niralpokal** [comment]
Going to close this since #549 updates to angular 12 support.

**Pull request closed without merging**
