### PR TITLE
Fix filter bug, fix problems when filter input is '' and fix type attribute in icons

### PR DESCRIPTION
**Pull request by clozanosanchez**
I rebased the three patches and made the test cases.

Regarding the problem when the filter input is '', I could not reproduce it again. However, I added a test case in order to check that the whole information is displayed when the component is initialised and no filter is entered.

### CODE REVIEW

**Comment by clozanosanchez** [comment]
@bekos Tests are failing but I do not find the problem. I did not change any configuration file and karma is executing 0 tests. Could you review why they are failing?

**Comment by bekos** [comment]
@clozanosanchez I see the error, it's really weird! I will need to investigate.
BTW you shouldn't mix the icon fix with the filter fix in the same commit/PR, since in general it will be harder for me to review.

**Comment by clozanosanchez** [comment]
I know, but I had problems to rebase the patches and at the end I had all together. Sorry. 

The previous code about filters was working properly. So, the problems started with the icons code.

**Comment by bekos** [comment]
@clozanosanchez Problem had nothing to do with your code. It was an error with npmcdn renamed to unpkg, which is the CDN we use to get the IE polyfills. You can rebase your code and it will be OK I suppose.

**Comment by clozanosanchez** [comment]
Everything working.

**Comment by bekos** [comment]
@clozanosanchez Thx. Can you please rebase and squash your commits?

**Comment by clozanosanchez** [comment]
@bekos Could you explain me how to do it, please?

**Comment by bekos** [comment]
@clozanosanchez Rebase is simple as `git rebase master` and about squashing to one commit, you can read here: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

If you think the situation is already messy, you can close this PR and open a new one containing just your own changes. Thanks again for your effort and time.

**Comment by clozanosanchez** [comment]
@bekos Now, you can merge it with the original repository.

Thanks for the information ;)

**Comment by bekos** [comment]
@clozanosanchez Landed on master. Thx! 👍

**Pull request closed without merging**
