### PR TITLE
Angular 12 migration

### PR DESCRIPTION
**Pull request by jesusbarcenilla**
This PR replace yarn with npm and update the project to angular 12. The changes in src/lib are just the minimum to fix TS compilation errors.

In the new version of angular we cannot use angular decorators inside a class that it is not decorated so I made the class abstract and I add @Directive(). I don't like it but It is the lightest workaround I could find.

### CODE REVIEW

**Comment by madve2** [comment]
@jesusbarcenilla thank you, it looks promising! Can you please also replace yarn with npm in `https://github.com/ng-lightning/ng-lightning/blob/master/.travis.yml` to ensure that CI works properly?

@bekos what do you think?

**Comment by bekos** [comment]
@jesusbarcenilla Nice job 👍  As @madve2 said, fix the tests so we can confirm it and review it 😃

**Review by madve2 — APPROVED** [review]

**Comment by bekos** [comment]
hi @jesusbarcenilla 🙂 can you squash your commits and change your commit message to follow this repo's conventions?
I think you should add a BREAKING CHANGE section also for Angular 12.

**Comment by jesusbarcenilla** [comment]
@bekos I'm not sure what do you mean with the BREAKING CHANGE section. There is no component changes and I have tested it with in my current project (angular 11) and it works fine.

**Comment by madve2** [comment]
@bekos I think it should be fine to merge this if we also bump the major version number on the next release... WDYT?

**Comment by bekos** [comment]
@jesusbarcenilla maybe it breaks for Angular 10, I'm not sure :) but to be safe I would suggest to at least mention on the CHANGELOG, and ofc as @madve2 said, we can increase the major version.
Also can you change your commit message to `feat: update to Angular v12` instead of `chore...`, it's an important update 😃

**Comment by jesusbarcenilla** [comment]
I have change the message and included the update the CHANGELOG following the pattern in previous angular updates but We have to include the link before releasing the next version.

**Comment by madve2** [comment]
@jesusbarcenilla thank you!

**Comment by simongroom** [comment]
is there a timeframe for these changes to be packaged in a new version?

**Comment by bekos** [comment]
@simongroom I plan to make a release on weekend

**Comment by simongroom** [comment]
> @simongroom I plan to make a release on weekend

@bekos thank you!

**Pull request merged**
