### PR TITLE
feat(app): add angular 4 support

### PR DESCRIPTION
**Pull request by kgalanop**

### CODE REVIEW

**Comment by Chyngyz** [comment]
Any news on accepting this?

**Comment by Adondriel** [comment]
Any reason why this hasn't been accepted yet?

**Comment by rotvulpix** [comment]
@bekos ping

**Comment by esarbanis** [comment]
@kgalanop Thank you for your effort, but ng 4 upgrade was tackled by @bekos in #342 . There were a few more things that needed to be done before we could completely upgrade.

Please keep only the animation support commit in this PR and update the title. We will be happy to review that.

**Comment by esarbanis** [comment]
Duplicate (#345) created, closing this one.

**Pull request closed without merging**
